Advenced_Django/Advenced_Django/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from basic import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('basic/', include('basic.urls')),
    path('', views.IndexView.as_view(), name='Home')
]

Advenced_Django/basic/urls.py
from django.conf.urls import url
from django.urls import path
from .views import StudentCreateView, SchoolDetailCreateView, SchoolDetailUpdateView,SchoolListView, SchoolDetailView, SchoolDeleteView, StudentCreateView


app_name = 'basic_app'
urlpatterns = [
    path('', SchoolListView.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/$',SchoolDetailView.as_view(),name='detail'),
    url(r'^create/$',SchoolDetailCreateView.as_view(),name='create'),
    url(r'^update(?P<pk>[-\w]+)/$',SchoolDetailUpdateView.as_view(),name='update'),
    url(r'delete(?P<pk>[-\w]+)/$', SchoolDeleteView.as_view(), name = 'delete'),
    url(r'^stdcreate/$',StudentCreateView.as_view(),name='stdcreate'),    
]

Advenced_Django/basic/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from django.db.models.fields import CharField
from django.urls import reverse

# Create your models here.
class School(models.Model):
    name = models.CharField(max_length=20)
    location = models.CharField(max_length=1000)
    principals = models.CharField(max_length=20)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("basic_app:detail",kwargs={'pk':self.pk})
        
class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name='students', on_delete=CASCADE)

    def __str__(self):
        return self.name

Advenced_Django/basic/views.py
from django.db.models import fields
from django.shortcuts import render
# use it for redirect to certain url
from django.urls import reverse_lazy
from django.views.generic import (View, TemplateView, 
                                    ListView, DetailView,
                                    CreateView, UpdateView, 
                                    DeleteView)
from . import models

# Create your views here.
class IndexView(TemplateView):
    template_name = 'index.html'

class SchoolListView(ListView):
    template_name = 'basic_app/school_list.html'
    context_object_name = 'schools'
    model = models.School
    
class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School   
    template_name = 'basic_app/school_detail.html'

class SchoolDetailUpdateView(UpdateView):
    fields = ('name', 'principals')
    model = models.School
    template_name = 'basic_app/school_form.html'

class SchoolDetailCreateView(CreateView):
    fields = ("name","principals","location")
    model = models.School
    template_name = 'basic_app/school_form.html'

class SchoolDeleteView(DeleteView):
    model = models.School
    context_object_name = 'school_detail'
    template_name = 'basic_app/delete_form.html'
    success_url = reverse_lazy('basic_app:list')

class StudentCreateView(CreateView):
    model = models.Student
    fields = ('name', 'age', 'school')
    template_name = 'basic_app/student_create.html'
    success_url = reverse_lazy('basic_app:detail')

Advenced_Django/basic/templates/basic_app/basic_app.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" />
		<title>Base</title>
	</head>
	<body>
		<nav class="navbar navbar-default navbar-static-top">
			<ul class="nav navbar-nav">
				<li><a class="navbar-band" href="{% url 'basic_app:list' %}">Schools</a></li>
				<li><a class="navbar-band" href="{% url 'admin:index' %}">Admin</a></li>
			</ul>
		</nav>

		<div class="container">{% block body_block %} {% endblock %}</div>
	</body>
</html>

Advenced_Django/basic/templates/basic_app/delete_form.html
{% extends 'basic_app/basic_app.html' %} {% block body_block %}

<h1>deleting {{school_detail.name}}</h1>

<form method="POST">
	{% csrf_token %}
	<input type="submit" class="btn btn-danger" value="Delete" />
</form>

{% endblock %}

Advenced_Django/basic/templates/basic_app/school_detail.html
{% extends 'basic_app/basic_app.html' %} {% block body_block %}
<div class="jumbtron">
	<h1>Welcome to the School Detail Page</h1>
	<h2 style="color: aqua">School Details:</h2>
	<p>Id_num: {{school_detail.id}}</p>
	<p>Name: {{school_detail.name}}</p>
	<p>Principal: {{school_detail.principals}}</p>
	<p>Location: {{school_detail.location}}</p>
	<h3>Students:</h3>

	{% for student in school_detail.students.all %}
	<p>{{student.name}} who is {{student.age}} years old.</p>
	{% endfor %}
</div>

<div>
	<p><a class="btn btn-warning" href="{% url 'basic_app:update' pk=school_detail.pk %}">Update</a></p>
	<p><a class="btn btn-danger" href="{% url 'basic_app:delete' pk=school_detail.pk %}">Delete</a></p>
	<p><a class="btn btn-primary" href="{% url 'basic_app:stdcreate' %}">Add Student</a></p>
</div>
{% endblock%}

Advenced_Django/basic/templates/basic_app/school_form.html
{% extends 'basic_app/basic_app.html' %} 


{% block body_block %}
<h1>
    {% if not form.instance.pk %}
    Create School
    {% else %}
    Update School
    {%endif%}
</h1>

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}

    <input type="submit" class="btn btn-primary" value="Submit" />
</form>

{% endblock%}

Advenced_Django/basic/templates/basic_app/school_list.html
{% extends 'basic_app/basic_app.html' %} {% block body_block %}

<h1>Welcome to a list of all the Schools</h1>
<ol>
	{% for school in schools %}
	<h2>
		<li><a href="{{school.id}}">{{school.name}}</a></li>
	</h2>
	{% endfor %}
</ol>
<p><a class="btn btn-warning" href="{% url 'basic_app:create' %}">Create</a></p>
{% endblock %}

Advenced_Django/basic/templates/basic_app/student_create.html
{% extends 'basic_app/basic_app.html' %} {% block body_block %}

<form method="POST">
	{% csrf_token %} {{ form.as_p }}

	<input type="submit" class="btn btn-primary" value="Submit" />
</form>

{% endblock%}

Advenced_Django/basic/templates/basic_app/update_form.html
{% extends 'basic_app/basic_app.html' %} {% block body_block %}

<h1>{% if not form.instance.pk %} Create School {% else %} Update School {% endif %}</h1>

<form method="POST">
	{% csrf_token %} {{ form.as_p }}

	<input type="submit" class="btn btn-primary" value="Submit" />
</form>

{% endblock %}

Advenced_Django/templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" />
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Document</title>
	</head>
	<body>
		<nav class="navbar navbar-default navbar-static-top">
			<div class="container">
				<ul class="nav navbar-nav">
					<li><a class="navbar-band" href="{% url 'basic_app:list' %}">Schools</a></li>
					<li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
				</ul>
			</div>
		</nav>
		<div class="container">
			{% block body_block %}
			<!-- Anything outside of this will be inherited if you extend -->
			{% endblock %}
		</div>
	</body>
</html>

Advenced_Django/templates/basic.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" />
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Document</title>
	</head>
	<body>
		<div class="container">
			{% block body_block %}
			<!-- Anything outside of this will be inherited if you extend -->
			{% endblock %}
		</div>
	</body>
</html>

Advenced_Django/templates/index.html
<!DOCTYPE html> {% extends 'base.html' %} {% block body_block %}
<h1>Homepage</h1>
{% endblock %}