21_06_12_project/template/base/urls.py
from django.urls import path
from base import views

# template tagging
app_name = 'base'

urlpatterns = [
    path('others/', views.others, name='others'),
    path('relative/', views.relatives, name='relatives'),
]

21_06_12_project/template/template/urls.py
from django.contrib import admin
from django.urls import path, include
from base import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('basic/', include('base.urls'))
]

21_06_12_project/template/base/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'base/index.html')

def others(request):
    return render(request, 'base/others.html')

def relatives(request):
    return render(request, 'base/relatives.html')

21_06_12_project/template/templates/base/basic.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" />

		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Document</title>
	</head>
	<body>
		<nav class="navbar navbar-default navbar-static-top">
			<div class="container">
				<ul class="nav navbar-nav">
					<li><a class="navbar-brand" href="{% url 'index' %}">Home</a></li>
					<li><a class="navbar-link" href="{% url 'base:others' %}">Other</a></li>
					<li><a class="navbar-link" href="{% url 'base:relatives' %}">Relative</a></li>
				</ul>
			</div>
		</nav>
		<div class="container">
			{% block body_block %}
			<!-- Anything outside of this will be inherited if you extend -->
			{% endblock %}
		</div>
	</body>
</html>

21_06_12_project/template/templates/base/index.html
<!DOCTYPE html> {% extends 'base/basic.html' %} {% block body_block %}
<h1>Welcome to the Homepage</h1>
{% endblock %}

21_06_12_project/template/templates/base/others.html
<!DOCTYPE html>
{% extends 'base/basic.html' %} {% block body_block %}
<h1>This is others</h1>
{% endblock %}

21_06_12_project/template/templates/base/relatives.html
<!DOCTYPE html>
{% extends 'base/basic.html' %} {% block body_block %}
<h1>This is relative</h1>
{% endblock %}